repos:
-   repo: local
    hooks:
    -   id: black
        name: black formatting
        entry: black
        description: "black: The uncompromising Python code formatter"
        language: python
        args: ["--line-length=78"]
    -   id: flake8
        name: flake8 file formatting
        entry: flake8
        description: "flake8: The wrapper for PyFlakes and pycodestyle "
        language: python
        args: ["--max-line-length=78"]
    -   id: mypy
        name: mypy formatting
        entry: mypy
        description: "mypy: The mypy Python code formatter"
        language: python
        args: ["--install-types"]
    -   id: isort
        name: isort checking imports
        entry: isort
        description: "isort: The sorting imports Python code formatter"
        language: python

