site_name: WiD Hackathon
nav:
- Home: index.md
- About: about.md
theme:
  name: material
  logo: img/wid-logo.png
  favicon: 'img/wid-logo.ico'
  palette:
#    scheme: youtube
#    scheme: slate
    primary: pink
    accent: red
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
