site_name: WiD Hackathon
nav:
- Home: about.md
- MkDocs: index.md
- Kaggle Data: kaggle_data.md
- Geopandas: geopandas.md

theme:
  name: material
  logo: img/wid-logo.png
  favicon: 'img/wid-logo.ico'
  palette:
#    scheme: youtube
    primary: pink
    accent: red
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
