site_name: WiD Hackathon
nav:
- Women's Safety: index.md
- Health Data: health_data.md
- Kaggle Data: kaggle_data.md
- NHS: nhs_public_data.md
- Geopandas: geopandas.md
- API Instructions: api_instructions.md

theme:
  name: material
  logo: img/wid-logo.png
  favicon: 'img/wid-logo.ico'
  palette:
#    scheme: youtube
    primary: pink
    accent: red
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
